name: build

on: [push]

jobs:
  build_wheels:
  name: Build wheels on windows-latest
  runs-on: windows-latest

  steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.9'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==2.1.1
    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir wheelhouse
    - uses: actions/upload-artifact@v2
      with:
        path: ./wheelhouse/*.whl